### PR TITLE
fixes issue preventing anim-enabled set back to true to work

### LINKED ISSUE #169: [Bug]: m-model animation fails to start playing immediately once switchin `anim-enabled` to true.
### Describe the bug

Setting a valid `anim` attribute for an `m-model` with the attribute `anim-enabled` to `false`, to later on set `anim-enabled` to `true`, and `anim-start-time` to the current document time, doesn't work to start playing the animation immediately. Instead, the animation only plays when the page is refreshed.

https://github.com/mml-io/mml/assets/33723163/e7590cdb-71e6-4216-a1e6-7e473cb1e13b

### Expected behavior

Presumably the animation should start playing as soon the `anim-enabled` attribute is set to `true` and the `anim-start-time` attribute is set to the current document time.

### How to reproduce the bug

1) Create an `m-model` with a proper asset and URL for the `anim` attribute, but set `anim-enabled` to `false`, and then append it to the document;
2) Based on user action, set the `m-model` `anim-enabled` attribute to `true`, `anim-loop` to `true`, `anim-start-time` to `document.timeline.currentTime`, and remove the attribute `anim-pause-time`.

The animation should start based on the animation clips present in the asset passed as a URL to the `anim` attribute. Instead, it doesn't. However, if the user refresh the page, the animation will be playing.

### Link to the code that reproduces this bug

https://github.com/TheCodeTherapy/3d-web-experience/blob/382e4e9e546b13fe0d36d3cd8d2a04a17b16460c/example/multi-user-3d-web-experience/server/mml-documents/example-cars.html

### Packages

mml-web

### Package versions

0.14.0

### Extra details

_No response_

### PR DESCRIPTION
**Pull request by TheCodeTherapy**
Resolves #169 

This PR aims to fix an issue that prevented the `m-model` `anim` attribute from being applied back correctly once its `anim-enabled` attribute was set to false.

---

**What kind of changes does your PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Tests
- [ ] Other, please describe:

**Does your PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe its impact and migration path for existing applications:

**Does your PR fulfill the following requirements?**

- [X] All tests are passing
- [X] The title references the corresponding issue # (if relevant)

### CODE REVIEW

File: e2e-tests/test/testing-utils.ts [hunk 1]
```diff
@@ -50,6 +50,16 @@ export async function setDocumentTime(page: puppeteer.Page, documentTime: number
...
+  await page.evaluate(async () => {
+    await new Promise<void>((resolve) => {
+      requestAnimationFrame(() => {
+        resolve();
+      });
+    });
+  });
+}
+
 export async function takeAndCompareScreenshot(page: puppeteer.Page, threshold = 0.02) {
```
Comment (MarcusLongmuir) [inline e2e-tests/test/testing-utils.ts:63]: I think it would make sense to use this helper in the `takeAndCompareScreenshot` so that we get this benefit each time we take a screenshot.

Comment (TheCodeTherapy) [reply e2e-tests/test/testing-utils.ts:63]: done

**Review by MarcusLongmuir — APPROVED** [review]

**Review by MarcusLongmuir — APPROVED** [review]
